Typed Linear Algebra: fcarouge::typed_linear_algebra_internal Namespace Reference
fcarouge::typed_linear_algebra_internal Namespace Reference
Classes
struct divides
Linear algebra divides expression type specialization point.
struct divides< Lhs, std::identity >
struct divides< Lhs, std::tuple< Types... > >
struct divides< std::identity, Rhs >
struct divides< std::identity, std::identity >
struct divides< std::identity, std::tuple< Types... > >
struct divides< std::tuple< Types... >, Rhs >
struct divides< std::tuple< Types... >, std::identity >
struct divides< std::tuple< Types1... >, std::tuple< Types2... > >
struct multiplies
struct multiplies< Lhs, std::identity >
struct multiplies< Lhs, std::tuple< Types... > >
struct multiplies< std::identity, Rhs >
struct multiplies< std::tuple< Types... >, Rhs >
struct multiplies< std::tuple< Types... >, std::identity >
struct multiplies< std::tuple< Types1... >, std::tuple< Types2... > >
struct repacker
struct repacker< Pack< Types... > >
struct tupler
Typedefs
template<typename Lhs , typename Rhs >
using quotient
template<typename Lhs , typename Rhs >
using product = std::invoke_result_t<multiplies<Lhs, Rhs>, Lhs, Rhs>
template<typename Pack >
using repack = repacker<Pack>::type
template<typename Type >
using underlying_t
template<typename Type , std::size_t RowIndex, std::size_t ColumnIndex>
using element
template<typename Type , std::size_t Size>
using tuple_n_type = typename tupler<Type, Size>::type
using identity_index = std::tuple<std::identity>
Functions
template<std::size_t Begin, std::size_t End, std::size_t Increment, typename Function >
constexpr void for_constexpr (Function &&function)
Variables
template<typename Pack >
constexpr std::size_t size {repacker<Pack>::size}
Typedef Documentation
element
template<typename Type , std::size_t RowIndex, std::size_t ColumnIndex> using fcarouge::typed_linear_algebra_internal::element
Initial value:
 std::remove_cvref_t<product<
    std::tuple_element_t<RowIndex,
                         typename std::remove_cvref_t<Type>::row_indexes>,
    std::tuple_element_t<ColumnIndex,
                         typename std::remove_cvref_t<Type>::column_indexes>>>
Definition at line 196 of file utility.hpp.
identity_index
using fcarouge::typed_linear_algebra_internal::identity_index = std::tuple<std::identity>
Definition at line 268 of file utility.hpp.
product
template<typename Lhs , typename Rhs > using fcarouge::typed_linear_algebra_internal::product = std::invoke_result_t<multiplies<Lhs, Rhs>, Lhs, Rhs>
Definition at line 118 of file utility.hpp.
quotient
template<typename Lhs , typename Rhs > using fcarouge::typed_linear_algebra_internal::quotient
Initial value:
    std::invoke_result_t<divides<Lhs, Rhs>, const Lhs &, const Rhs &>
Definition at line 57 of file utility.hpp.
repack
template<typename Pack > using fcarouge::typed_linear_algebra_internal::repack = repacker<Pack>::type
Definition at line 179 of file utility.hpp.
tuple_n_type
template<typename Type , std::size_t Size> using fcarouge::typed_linear_algebra_internal::tuple_n_type = typename tupler<Type, Size>::type
Definition at line 266 of file utility.hpp.
underlying_t
template<typename Type > using fcarouge::typed_linear_algebra_internal::underlying_t
Initial value:
    std::remove_cvref_t<decltype(std::declval<std::remove_cvref_t<Type>>()(0,
                                                                           0))>
Definition at line 184 of file utility.hpp.
Function Documentation
for_constexpr()
template<std::size_t Begin, std::size_t End, std::size_t Increment, typename Function > void fcarouge::typed_linear_algebra_internal::for_constexpr (Function && function) constexpr
Definition at line 160 of file utility.hpp.
{
  if constexpr (Begin < End) {
    function(std::integral_constant<std::size_t, Begin>());
    for_constexpr<Begin + Increment, End, Increment>(
        std::forward<Function>(function));
  }
}
References for_constexpr().
Referenced by for_constexpr(), and std::formatter< fcarouge::typed_matrix< Matrix, RowIndexes, ColumnIndexes >, Char >::format().
Variable Documentation
size
template<typename Pack > std::size_t fcarouge::typed_linear_algebra_internal::size {repacker<Pack>::size} constexpr
Definition at line 181 of file utility.hpp.
{repacker<Pack>::size};