name: 'ClangTidy'

on:
  push:
    branches: [ 'master' ]
  pull_request:
    branches: [ 'master' ]
  schedule:
  - cron: '0 0 * * */5'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-26.04
    permissions:
      contents: read
    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@b09bb98e06d4d774595224525879c09bc6e98c40 # v2.20.1
      with:
        egress-policy: audit
    - name: Checkout
      uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: 'Install: Latest CMake'
      uses: ssrobins/install-cmake@da13ba26f50a41d3b03cfe8ca7265903f04a8932 # v1.0.0
    - name: 'Install: libc++'
      run: |
        sudo apt update
        sudo apt install -y "libc++-20-dev" "libc++abi-20-dev"
    - name: 'Configure'
      env:
        CXX: 'clang++-20'
        CC: 'clang-20'
      run: cmake -S . -B 'build' -DCMAKE_EXPORT_COMPILE_COMMANDS=ON
    - name: Verify
      run: |
        FILES=`find . \
          -type f \( \
            -path './benchmark/*.cpp' -o \
            -path './sample/*.cpp' -o \
            -path './support/*.cpp' -o \
            -path './test/*.cpp' \) \
            ! -name '*_fail.cpp'`
        run-clang-tidy -j 4 -p 'build' $FILES
